
input:
  gcc DataInput.c -g -o input

all:
  gcc Semaphore.c -g -o sem
  gcc Weatherforecast.c -g -o pred
  gcc ReadData.c -g -o read
  ./sem
  ./pred
  ./read


clean:
  rm input sem pred read *.txt
